add docker support
sanmusen214/BAAH pull request #148
Opened 2024-12-17 07:06 UTC by lonzzi

#108

- [x] 支持通过环境变量传递参数
- [x] 添加了 Dockerfile 和 docker-compose.yml, 能够直接通过 `docker compose up -d` 启动
- [ ] 预计添加一个启动脚本支持拉取新代码
- [ ] 可能添加的 github action 支持

#147, 不小心 -f 把 commit 丢了（

2024-12-17 08:17 UTC, lonzzi reviewed
github action 支持编译出 x86 和 arm64 镜像，目前 `git pull` 只在容器启动的时候执行，添加了一个换源的 `Dockerfile`。

2024-12-17 08:26 UTC, sanmusen214 requested changes
补一下文档说明（

2024-12-17 08:42 UTC, lonzzi commented
> 补一下文档说明（

补充好了

2024-12-18 07:32 UTC, sanmusen214 approved these changes

2024-12-18 07:33 UTC, merged