#56
sanmusen214/BAAH pull request #94
Opened 2024-08-02 10:22 UTC by LLL1997

https://github.com/sanmusen214/BAAH/issues/56
测试了以下
普通&困难：简中服，日服，国际服
学院：简中服，日服，国际服
特殊：日服，国际服

2024-08-02 11:30 UTC, sanmusen214 requested changes
modules/AllPage/Page.py    “用于交战时..."是对COLOR_BUTTON_WHITE的注释，新加的COLOR_PINK不应该放在它们中间

modules/AllTask/InSpecial/InSpecial.py    我看你在主逻辑里写了一些点击操作，是为了进入到关卡选择页面比色嘛。与其在进入一次关卡选择页面比色后返回上级页面，不如把比色操作放到后面 进入location 动作之后，如果比色失败就直接返回。根据活动是否在进行判断是否执行任务应当是一个额外动作，不能添加会影响到主逻辑的side effect。

2024-08-04 11:05 UTC, LLL1997 commented
改正了代码，森哥有空看下

2024-08-04 13:43 UTC, sanmusen214 commented
话说悬赏通缉不会有双倍吗，好像没看到你写悬赏通缉这块

2024-08-05 02:18 UTC, LLL1997 commented
有双倍和三倍，但是这种操作得提前获取活动开始的时间数据，然后提前不打才能实现好的效果，且需要购买大月卡和月卡，要屯票的也是手动较多，所以没写

2024-08-05 02:19 UTC, LLL1997 commented
这个逻辑应该还可以改成多点颜色匹配，现在单点颜色匹配感觉不太靠谱，晚点我修改下

2024-08-05 07:19 UTC, sanmusen214 approved these changes

2024-08-05 07:23 UTC, sanmusen214 commented
单点匹配其实也还好，固定位置的像素点值不会有变化的

2024-08-10 22:38 UTC, merged