添加了 web 端的登陆验证，运行 py 文件时能够读取并解析 args
sanmusen214/BAAH pull request #96
Opened 2024-08-03 14:25 UTC by lonzzi

1. web 端鉴权代码来自 [examples/authentication/main.py](https://github.com/zauberzeug/nicegui/blob/main/examples/authentication/main.py), 在此基础上使用了 `bcrypt` 库对密码进行了简单的加密处理。
2. 现在能够解析 args 进行更多配置了，具体配置项如下：

| 配置项 | 默认值    | 备注 |
| ------ | --------- | ---- |
| host   | 127.0.0.1 | web 端地址 |
| auth   | False     | 是否开启 web 端鉴权 |
| username | admin | 用户名称 |
| password | admin | 用户密码 |

2024-08-03 17:30 UTC, sanmusen214 requested changes
请先提一个Feature Request Issue讨论下新feature。

GUI的多参解析这个点子不错。
但是另一个账户密码登录有点复杂了，是为了部署到服务器上发布到公网访问防止别人使用吗，加认证中间件和额外的加解密库有点复杂了，加库意味着每个更新包都得包含这个库发布，或者更新为大版本。maybe试试直接比对启动时指定的token参数和用户输入的值，比对成功再refresh渲染主要组件。

2024-08-03 17:50 UTC, lonzzi commented
> 请先提一个Feature Request Issue讨论下新feature。
> 
> GUI的多参解析这个点子不错。 但是另一个账户密码登录有点复杂了，是为了部署到服务器上发布到公网访问防止别人使用吗，加认证中间件和额外的加解密库有点复杂了，加库意味着每个更新包都得包含这个库发布，或者更新为大版本。maybe试试直接比对启动时指定的token参数和用户输入的值，比对成功再 [refresh](https://nicegui.io/documentation/refreshable) 渲染主要组件。

好的，我去开个 issue 来讨论这个问题。

2024-08-03 19:56 UTC, sanmusen214 approved these changes

2024-08-03 19:57 UTC, merged

2024-09-24 05:40 UTC, sanmusen214 commented
@ly5519 
这是当前release版本的GUI启动时参数列表

| 配置项 | 默认值    | 备注 |
| ------ | --------- | ---- |
| host   | 127.0.0.1 | web 端地址 |
| port   | auto     | web端端口 |
| token | None | web端验证密钥 |